knp_snappy:
  pdf:
    enabled: true
    binary: '/usr/bin/wkhtmltopdf'
    options:
      enable-local-file-access: true
      encoding: UTF-8
      page-size: A4
      lowquality: false
      margin-top: 15
      margin-right: 15
      margin-bottom: 15
      margin-left: 15
  image:
    enabled: true
    binary: '/usr/bin/wkhtmltoimage'
    options: []
