knp_snappy:
    pdf:
        enabled:    true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"' 
        options:    
              enable-local-file-access: true  # Important for file permissions
              encoding: 'UTF-8'
        
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
