<?php
// Basic test script for wkhtmltopdf

// Path to wkhtmltopdf
$wkhtmltopdf = '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"';

// Simple HTML content
$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>PDF Test</title>
    <style>
        body { font-family: Arial, sans-serif; }
        h1 { color: blue; }
    </style>
</head>
<body>
    <h1>PDF Test</h1>
    <p>This is a test PDF generated by wkhtmltopdf.</p>
    <p>Current time: ' . date('Y-m-d H:i:s') . '</p>
</body>
</html>
';

// Create a temporary HTML file
$tmpHtmlFile = tempnam(sys_get_temp_dir(), 'pdf_test_') . '.html';
file_put_contents($tmpHtmlFile, $html);

// Output PDF file
$outputPdf = tempnam(sys_get_temp_dir(), 'pdf_output_') . '.pdf';

// Command to generate PDF
$command = $wkhtmltopdf . ' --enable-local-file-access ' . $tmpHtmlFile . ' ' . $outputPdf;

// Execute command
$returnValue = 0;
$output = [];
exec($command, $output, $returnValue);

if ($returnValue === 0) {
    // Command executed successfully
    
    // Set headers for PDF download
    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="test.pdf"');
    header('Cache-Control: private, max-age=0, must-revalidate');
    header('Pragma: public');
    
    // Output the PDF
    readfile($outputPdf);
    
    // Clean up
    @unlink($tmpHtmlFile);
    @unlink($outputPdf);
} else {
    // Command failed
    header('Content-Type: text/plain');
    echo "Error executing wkhtmltopdf:\n";
    echo "Command: $command\n";
    echo "Return value: $returnValue\n";
    echo "Output:\n";
    echo implode("\n", $output);
} 